(() => {
  'use strict';
  const ADMIN_EMAIL='shivgarg597@gmail.com';
  const cfg=window.VYBE_CONFIG||{};
  const SUPABASE_URL=cfg.supabaseUrl, SUPABASE_KEY=cfg.supabaseAnonKey;
  const ready=Boolean(SUPABASE_URL&&SUPABASE_KEY&&window.supabase);
  let db=null,user=null;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__vybeAdminToast);window.__vybeAdminToast=setTimeout(()=>x.classList.remove('show'),2200)};
  const show=(el,on=true)=>el.classList.toggle('hidden',!on);
  const slug=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const cfgError='Add your Supabase URL and public anon key to vybe-config.js first.';

  function fail(msg){$('#loginMessage').textContent=msg;}
  function openEditor(title,html,onSave){
    $('#editorTitle').textContent=title; $('#editorForm').innerHTML=html; show($('#editor')); $('#editor').setAttribute('aria-hidden','false');
    $('#editorForm').onsubmit=async e=>{e.preventDefault();try{await onSave(new FormData(e.currentTarget));closeEditor()}catch(err){toast(err.message||'Save failed')}};
  }
  function closeEditor(){show($('#editor'),false);$('#editor').setAttribute('aria-hidden','true');}
  function input(name,label,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`}
  function select(name,label,value,options){return `<label>${esc(label)}<select name="${esc(name)}">${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`}

  async function requireAdmin(){
    if(!ready){fail(cfgError);return false}
    db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
    const {data,error}=await db.auth.getUser();
    if(error||!data.user){return false}
    user=data.user;
    if(user.email?.toLowerCase()!==ADMIN_EMAIL){await db.auth.signOut();fail('Access denied. This Studio is private.');return false}
    const {data:p,error:pe}=await db.from('profiles').select('role').eq('id',user.id).single();
    if(pe||p?.role!=='admin'){await db.auth.signOut();fail('Access denied. Admin role is not active for this account.');return false}
    $('#adminEmail').textContent=user.email;show($('#loginView'),false);show($('#appView'));
    await refreshAll(); return true;
  }

  async function login(e){e.preventDefault();if(!ready){fail(cfgError);return}db=db||window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;if(email!==ADMIN_EMAIL){fail('Access denied.');return}const {error}=await db.auth.signInWithPassword({email,password});if(error){fail('Sign-in failed. Check the credentials.');return}await requireAdmin()}

  async function query(table,select='*'){const {data,error}=await db.from(table).select(select);if(error)throw error;return data||[]}
  async function refreshAll(){try{const [songs,artists,requests,subs,users]=await Promise.all([query('songs','id,title,slug,language,genre,mood,bpm,duration_seconds,status,audio_path,cover_path,lyrics,artist_id,created_at,artists(name)'),query('artists','id,name,slug,genre,language,bio,website,avatar_path'),query('song_requests','id,title,artist,reason,region,language,votes,status,created_at'),query('artist_submissions','id,artist_name,contact_email,song_title,genre,language,description,source_url,audio_path,artwork_path,lyrics,rights_confirmed,status,reviewer_note,created_at,reviewed_at'),query('profiles','id,display_name,username,role,created_at')]);window.__vybeAdmin={songs,artists,requests,subs,users};renderDashboard();renderSongs();renderArtists();renderRequests();renderSubmissions();renderUsers()}catch(e){toast(e.message||'Could not load data')}}

  function renderDashboard(){const d=window.__vybeAdmin||{};$('#stats').innerHTML=[['Songs',d.songs?.length||0],['Published',(d.songs||[]).filter(x=>x.status==='published').length],['Artists',d.artists?.length||0],['Review queue',(d.subs||[]).filter(x=>x.status==='submitted'||x.status==='under_review').length]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('')}
  function renderSongs(){const a=window.__vybeAdmin?.songs||[];$('#songsList').innerHTML=a.length?a.map(s=>`<div class="row"><div class="row-main"><strong>${esc(s.title)}</strong><p>${esc(s.artists?.name||'No artist')} · ${esc(s.language||'')} · ${esc(s.genre||'')} · ${esc(s.mood||'')}</p><small>${s.status} · ${s.duration_seconds||0}s · ${s.audio_path?'audio attached':'no audio'}</small></div><div class="row-actions"><span class="status">${esc(s.status)}</span><button class="ghost" data-edit-song="${s.id}">Edit</button>${s.status==='published'?`<button class="ghost" data-unpublish="${s.id}">Unpublish</button>`:`<button class="primary" data-publish="${s.id}">Publish</button>`}<button class="ghost" data-delete-song="${s.id}">Delete</button></div></div>`).join(''):'<div class="panel">No songs yet. Add your first song.</div>';}
  function renderArtists(){const a=window.__vybeAdmin?.artists||[];$('#artistsList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.name)}</strong><p>${esc(x.genre||'')} · ${esc(x.language||'')}</p><small>${esc(x.slug)}</small></div><div class="row-actions"><button class="ghost" data-edit-artist="${x.id}">Edit</button><button class="ghost" data-delete-artist="${x.id}">Delete</button></div></div>`).join(''):'<div class="panel">No artists yet.</div>'}
  function renderRequests(){const a=(window.__vybeAdmin?.requests||[]).slice().sort((x,y)=>y.votes-x.votes);$('#requestsList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.title)} — ${esc(x.artist)}</strong><p>${esc(x.reason||'No reason provided')}</p><small>♥ ${x.votes} · ${esc(x.region||'')} · ${esc(x.language||'')} · ${new Date(x.created_at).toLocaleString()}</small></div><div class="row-actions">${['requested','reviewing','approved','declined'].map(st=>`<button class="ghost" data-request-status="${esc(st)}" data-id="${x.id}">${esc(st)}</button>`).join('')}<button class="ghost" data-delete-request="${x.id}">Delete</button></div></div>`).join(''):'<div class="panel">No requests yet.</div>'}
  function renderSubmissions(){const a=window.__vybeAdmin?.subs||[];$('#submissionsList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.song_title)}</strong><p>${esc(x.artist_name)} · ${esc(x.contact_email)} · ${esc(x.genre||'')} · ${esc(x.language||'')}</p><small>${x.audio_path?'audio uploaded':'no audio'} · rights ${x.rights_confirmed?'confirmed':'not confirmed'} · ${new Date(x.created_at).toLocaleString()}</small><div><span class="status">${esc(x.status)}</span></div></div><div class="row-actions"><button class="ghost" data-sub-status="under_review" data-id="${x.id}">Review</button><button class="primary" data-sub-status="approved" data-id="${x.id}">Approve</button><button class="ghost" data-sub-status="changes_required" data-id="${x.id}">Changes</button><button class="ghost" data-sub-status="rejected" data-id="${x.id}">Reject</button></div></div>`).join(''):'<div class="panel">No artist submissions yet.</div>'}
  function renderUsers(){const a=window.__vybeAdmin?.users||[];$('#usersList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.display_name||x.username||'VYBE user')}</strong><small>${esc(x.username||'')} · ${esc(x.role)} · ${new Date(x.created_at).toLocaleString()}</small></div><span class="status">${esc(x.role)}</span></div>`).join(''):'<div class="panel">No profiles yet.</div>'}

  function songForm(song={}){const artists=window.__vybeAdmin?.artists||[];return `<div class="form-grid">${input('title','Song title',song.title||'','','required')}${input('slug','Slug',song.slug||'','','required')}${select('artist_id','Artist',song.artist_id||'', [['','No artist'],...artists.map(a=>[a.id,a.name])].map(x=>x[0]).length?[]:[])}${input('language','Language',song.language||'')}${input('genre','Genre',song.genre||'')}${input('mood','Mood',song.mood||'')}${input('bpm','BPM',song.bpm||100,'number','min="1" max="300"')}${input('duration_seconds','Duration seconds',song.duration_seconds||0,'number','min="0"')}${select('status','Status',song.status||'draft',['draft','submitted','published','unlisted','rejected'])}${select('source_type','Source',song.source_type||'artist_upload',['artist_upload','licensed_api','vybe_original','external'])}${input('source_url','Source URL',song.source_url||'','url')}${input('audio_url','Audio URL (optional)',song.audio_url||'','url')}${input('cover_url','Cover URL (optional)',song.cover_url||'','url')}<label class="span2">Lyrics<textarea name="lyrics" placeholder="Paste authorised lyrics">${esc(song.lyrics||'')}</textarea></label><label class="span2">Audio file (admin only)<input name="audio_file" type="file" accept="audio/*"></label><label class="span2">Artwork file (admin only)<input name="artwork_file" type="file" accept="image/*"></label><p class="form-note span2">Use admin-owned/licensed audio and lyrics only. Uploaded files are stored in Supabase Storage.</p></div>`}

  function artistForm(a={}){return `<div class="form-grid">${input('name','Artist name',a.name||'','','required')}${input('slug','Slug',a.slug||'','','required')}${input('genre','Genre',a.genre||'')}${input('language','Language',a.language||'')}<label class="span2">Bio<textarea name="bio">${esc(a.bio||'')}</textarea></label>${input('website','Website',a.website||'','url')}${input('avatar_path','Avatar path / URL',a.avatar_path||'')}</div>`}

  async function upload(pathPrefix,file,bucket){if(!file||!file.size)return null;const clean=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=`admin/${Date.now()}-${clean}`;const {error}=await db.storage.from(bucket).upload(`${pathPrefix}/${path}`,file,{upsert:false,contentType:file.type});if(error)throw error;return `${pathPrefix}/${path}`}
  async function saveSong(fd,id){let audio_path=fd.get('audio_url')||null,cover_path=fd.get('cover_url')||null;const af=fd.get('audio_file'),cf=fd.get('artwork_file');if(af&&af.size)audio_path=await upload('songs',af,cfg.musicBucket||'music');if(cf&&cf.size)cover_path=await upload('covers',cf,cfg.artworkBucket||'artwork');const payload={title:String(fd.get('title')),slug:String(fd.get('slug')||slug(fd.get('title'))),artist_id:fd.get('artist_id')||null,language:String(fd.get('language')||''),genre:String(fd.get('genre')||''),mood:String(fd.get('mood')||''),bpm:Number(fd.get('bpm')||100),duration_seconds:Number(fd.get('duration_seconds')||0),status:String(fd.get('status')||'draft'),source_type:String(fd.get('source_type')||'artist_upload'),source_url:String(fd.get('source_url')||''),lyrics:String(fd.get('lyrics')||''),audio_path,cover_path,created_by:user.id,published_at:fd.get('status')==='published'?new Date().toISOString():null};const res=id?await db.from('songs').update(payload).eq('id',id):await db.from('songs').insert(payload);if(res.error)throw res.error;toast('Song saved');await refreshAll()}

  async function saveArtist(fd,id){const payload={name:String(fd.get('name')),slug:String(fd.get('slug')||slug(fd.get('name'))),genre:String(fd.get('genre')||''),language:String(fd.get('language')||''),bio:String(fd.get('bio')||''),website:String(fd.get('website')||''),avatar_path:String(fd.get('avatar_path')||''),owner_id:id?undefined:user.id};const res=id?await db.from('artists').update(payload).eq('id',id):await db.from('artists').insert(payload);if(res.error)throw res.error;toast('Artist saved');await refreshAll()}

  async function updateSongStatus(id,status){const {error}=await db.from('songs').update({status,published_at:status==='published'?new Date().toISOString():null}).eq('id',id);if(error)throw error;await refreshAll();toast(`Song ${status}`)}
  async function deleteSong(id){if(!confirm('Delete this song?'))return;const {error}=await db.from('songs').delete().eq('id',id);if(error)throw error;await refreshAll();toast('Song deleted')}
  async function deleteArtist(id){if(!confirm('Delete this artist? Songs keep their records but lose the artist link.'))return;const {error}=await db.from('artists').delete().eq('id',id);if(error)throw error;await refreshAll();toast('Artist deleted')}
  async function updateRequest(id,status){const {error}=await db.from('song_requests').update({status}).eq('id',id);if(error)throw error;await refreshAll();toast('Request updated')}
  async function deleteRequest(id){if(!confirm('Delete request?'))return;const {error}=await db.from('song_requests').delete().eq('id',id);if(error)throw error;await refreshAll();toast('Request deleted')}
  async function updateSubmission(id,status){const {error}=await db.from('artist_submissions').update({status,reviewed_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await refreshAll();toast(`Submission ${status.replace('_',' ')}`)}

  function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}

  async function init(){if(!ready){fail(cfgError);return}db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);await requireAdmin();$('#loginForm').addEventListener('submit',login);$('#logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});$('#closeEditor').addEventListener('click',closeEditor);$('#refreshAll').addEventListener('click',refreshAll);document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>switchTab(b.dataset.jump));$('#newSong').onclick=()=>openEditor('Add song',songForm(),fd=>saveSong(fd));$('#newArtist').onclick=()=>openEditor('Add artist',artistForm(),fd=>saveArtist(fd));}

  document.addEventListener('click',async e=>{try{const b=e.target.closest('button');if(!b)return;if(b.dataset.editSong){const s=(window.__vybeAdmin.songs||[]).find(x=>x.id===b.dataset.editSong);openEditor('Edit song',songForm(s),fd=>saveSong(fd,s.id))}else if(b.dataset.deleteSong)await deleteSong(b.dataset.deleteSong);else if(b.dataset.publish)await updateSongStatus(b.dataset.publish,'published');else if(b.dataset.unpublish)await updateSongStatus(b.dataset.unpublish,'unlisted');else if(b.dataset.editArtist){const a=(window.__vybeAdmin.artists||[]).find(x=>x.id===b.dataset.editArtist);openEditor('Edit artist',artistForm(a),fd=>saveArtist(fd,a.id))}else if(b.dataset.deleteArtist)await deleteArtist(b.dataset.deleteArtist);else if(b.dataset.requestStatus)await updateRequest(b.dataset.id,b.dataset.requestStatus);else if(b.dataset.deleteRequest)await deleteRequest(b.dataset.deleteRequest);else if(b.dataset.subStatus)await updateSubmission(b.dataset.id,b.dataset.subStatus)}catch(err){toast(err.message||'Action failed')}});
  init();
})();