/* VYBE — single runtime
   Curated music demo + player + lyrics + visual engine + requests + submissions + local studio.
   The static GitHub Pages build stores demo data in localStorage; shared multi-user data needs a backend later.
*/
(() => {
  const $ = (id) => document.getElementById(id);
  const $$ = (sel) => [...document.querySelectorAll(sel)];
  const reduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  const defaultTracks = [
    {title:'Night Drive',artist:'VYBE Radio · Demo',bpm:108,mood:'Dreamy · Night',tags:['all','india','new','night','dreamy'],duration:150,art:'art-a',lyrics:['City lights are breathing slow','We disappear where neon glows','Every second pulls me closer','Lose the world and find the motion','Midnight turns the silence gold','Stay inside this afterglow']},
    {title:'Afterglow',artist:'VYBE Radio · Demo',bpm:96,mood:'Warm · Global',tags:['all','global','love','chill'],duration:192,art:'art-b',lyrics:['Golden hours fade to blue','I keep every thought of you','Slowly turning into light','We can stay here all night']},
    {title:'Midnight Rain',artist:'VYBE Radio · Demo',bpm:82,mood:'Blue · India',tags:['all','india','sad','night'],duration:172,art:'art-c',lyrics:['Rain is falling on the glass','Memories are moving fast','Every street becomes a song','I have known this road so long']},
    {title:'Neon Hearts',artist:'VYBE Radio · Demo',bpm:124,mood:'Electric · Fresh',tags:['all','global','new','hype','party'],duration:161,art:'art-d',lyrics:['Neon hearts are running wild','Turn the city into light','Bass is drawing every line','We are electric tonight']},
    {title:'Desi Moon',artist:'VYBE Sessions · Demo',bpm:104,mood:'Warm · India',tags:['all','india','love','new'],duration:178,art:'art-b',lyrics:['Moonlight on a quiet road','Every beat becomes a code','Stay a little, stay with me','Let the night set us free']},
    {title:'Velocity',artist:'VYBE Sessions · Demo',bpm:132,mood:'Hype · Fresh',tags:['all','global','new','hype','workout'],duration:146,art:'art-d',lyrics:['Push the skyline out of frame','Every second calls my name','Faster now, we never slow','Feel the city overflow']}
  ];

  const saved = JSON.parse(localStorage.getItem('vybeState') || '{}');
  let tracks = Array.isArray(saved.tracks) && saved.tracks.length ? saved.tracks : defaultTracks;
  let idx = 0, pos = 0, playing = false, muted = false, motion = !reduced, timer = null, audioCtx = null, masterGain = null, wakeLock = null;
  let liked = new Set(saved.liked || []);
  let requests = Array.isArray(saved.requests) ? saved.requests : [
    {id:1,title:'Kesariya',artist:'Popular request',votes:127,status:'Requested'},
    {id:2,title:'Iktara',artist:'Popular request',votes:94,status:'Requested'}
  ];
  let submissions = Array.isArray(saved.submissions) ? saved.submissions : [];
  let playlists = Array.isArray(saved.playlists) && saved.playlists.length ? saved.playlists : [{id:'my-vybe',name:'My VYBE',tracks:[]}];
  let mood = saved.mood || 'all';

  const els = {
    pre:$('preloader'), preP:$('preloaderProgress'), preL:$('preloaderLabel'), nav:$('siteNav'), cursor:$('cursor'), cursorLabel:$('cursorLabel'),
    scroll:$('scrollProgress'), space:$('space'), world:$('heroWorld'), rig:$('albumRig'), album:$('albumCard'), albumTitle:$('albumTitle'), albumBpm:$('albumBpm'), albumNumber:$('albumNumber'),
    heroTrack:$('heroTrack'), heroArtist:$('heroArtist'), heroEnergy:$('heroEnergy'), heroMood:$('heroMood'), signalBpm:$('signalBpm'), sceneTrack:$('sceneTrack'), sceneMood:$('sceneMood'),
    lyricName:$('lyricsTrackName'), lyricClock:$('lyricClock'), lyricDuration:$('lyricsDuration'), lyricProgress:$('lyricsProgress'), lyricCopy:$('lyricsCopy'),
    playerTitle:$('playerTitle'), playerArtist:$('playerArtist'), playerThumb:$('playerThumb'), current:$('currentTime'), duration:$('duration'), progress:$('progress'), play:$('playButton'), dockPlay:$('dockPlay'), bars:$('signalBars'),
    search:$('searchModal'), searchInput:$('searchInput'), searchResults:$('searchResults'), more:$('moreSheet')
  };

  function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
  function persist(){localStorage.setItem('vybeState',JSON.stringify({tracks,liked:[...liked],requests,submissions,playlists,mood}))}
  function showToast(text){let t=$('vybeToast');if(!t){t=document.createElement('div');t.id='vybeToast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2200)}
  function viewTransition(fn){try{if(document.startViewTransition&&!reduced)return document.startViewTransition(fn);fn()}catch{fn()}}

  function injectFeatureStyles(){
    const s=document.createElement('style');s.id='vybeFeatureStyles';s.textContent=`
      .preloader.loaded{opacity:0;visibility:hidden;pointer-events:none;transition:opacity .75s ease,visibility .75s ease}
      .preloader.loaded .preloader-mark{transform:scale(.86);opacity:0;transition:transform .7s ease,opacity .5s ease}
      .vybe-modal{position:fixed;inset:0;z-index:120;background:rgba(4,4,8,.74);backdrop-filter:blur(24px);display:none;align-items:flex-end;justify-content:center;padding:18px}.vybe-modal.open{display:flex}
      .vybe-panel{width:min(980px,100%);max-height:min(88vh,900px);overflow:auto;border:1px solid rgba(255,255,255,.1);background:linear-gradient(160deg,rgba(25,25,34,.98),rgba(8,8,12,.98));border-radius:28px;padding:24px;box-shadow:0 40px 120px rgba(0,0,0,.55)}
      .vybe-panel h3{font-size:clamp(28px,4vw,54px);letter-spacing:-.06em;margin:2px 0 18px}.vybe-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.vybe-close{width:40px;height:40px;border:1px solid rgba(255,255,255,.12);border-radius:50%;font-size:24px}.vybe-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.vybe-card{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:rgba(255,255,255,.025)}.vybe-card strong{display:block;font-size:16px}.vybe-card small,.vybe-card p{display:block;color:#85858f;font-size:12px;line-height:1.55}.vybe-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.vybe-btn{border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:11px 14px;background:rgba(255,255,255,.03);font-size:11px}.vybe-btn.primary{background:#fff;color:#07070a}.vybe-input,.vybe-select,.vybe-textarea{width:100%;box-sizing:border-box;margin:6px 0 12px;padding:13px 14px;border-radius:13px;border:1px solid rgba(255,255,255,.1);background:#0b0b10;color:#fff;outline:none}.vybe-textarea{min-height:100px;resize:vertical}.vybe-label{display:block;font-size:10px;letter-spacing:.14em;color:#80818a;text-transform:uppercase;margin-top:10px}.vybe-pill{display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;background:rgba(139,124,255,.12);border:1px solid rgba(139,124,255,.25);font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#bab2ff}.vybe-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:16px}.vybe-tab.active{background:#fff;color:#07070a}.vybe-empty{padding:28px 0;color:#767780;text-align:center}.vybe-stat{display:flex;justify-content:space-between;gap:15px;padding:12px 0;border-bottom:1px solid rgba(255,255,255,.06)}.vybe-stat:last-child{border-bottom:0}.vybe-stat strong{font-size:14px}.vybe-stat span{color:#83848d;font-size:11px}.vybe-request-row,.vybe-review-row{padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:16px;margin-bottom:10px}.vybe-request-row .line,.vybe-review-row .line{display:flex;justify-content:space-between;gap:12px}.vybe-row-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.feature-launcher{display:flex;gap:8px;margin-top:22px;flex-wrap:wrap}.mobile-dock{z-index:88}
      #vybeParticles{position:fixed;inset:0;pointer-events:none;z-index:1;mix-blend-mode:screen;opacity:.55}.hero-world{touch-action:pan-y}.album-card.is-beat{box-shadow:0 55px 130px rgba(0,0,0,.55),0 0 140px rgba(139,124,255,.34);}
      #vybeToast{position:fixed;left:50%;bottom:92px;transform:translate(-50%,20px);z-index:200;padding:11px 15px;border-radius:999px;background:#fff;color:#07070a;font-size:11px;opacity:0;pointer-events:none;transition:.3s;box-shadow:0 12px 40px rgba(0,0,0,.35)}#vybeToast.show{opacity:1;transform:translate(-50%,0)}
      @media(max-width:760px){.desktop-nav{display:none!important}.vybe-panel{padding:18px;border-radius:22px;max-height:90vh}.vybe-grid{grid-template-columns:1fr}.vybe-modal{padding:8px}.feature-launcher{margin-top:15px}.hero-side-note{display:none}.player-extra{gap:5px}.player-extra button{padding:4px}.display-title{font-size:clamp(50px,16vw,92px)}.hero-world{min-height:420px;height:52vh}.album-rig{width:min(78vw,430px)}.floating-info{min-width:130px;padding:10px 11px}.info-left{left:-2%}.info-right{right:-2%}}
      @media(min-width:1600px){.hero{padding-left:10vw;padding-right:10vw}.section{padding-left:10vw;padding-right:10vw}.display-title{font-size:clamp(80px,7vw,170px)}.section-intro h2,.visual-heading h2,.artist-intro h2{font-size:clamp(64px,6vw,130px)}}
      @media(min-width:2200px){body{font-size:18px}.hero{min-height:100vh}.player-bar{left:7vw;right:7vw}.desktop-nav{gap:40px}.nav-actions{gap:12px}}
      @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}.cursor{display:none}body,button,a{cursor:auto}}
    `;document.head.appendChild(s)
  }

  function closeModal(id){const m=$(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}
  function openModal(id){const m=$(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false')}}
  function modalShell(id,title,body){const old=$(id);if(old)old.remove();const m=document.createElement('div');m.className='vybe-modal';m.id=id;m.setAttribute('aria-hidden','true');m.innerHTML=`<div class="vybe-panel"><div class="vybe-panel-head"><div><div class="eyebrow">VYBE SYSTEM</div><h3>${title}</h3></div><button class="vybe-close" data-close="${id}" aria-label="Close">×</button></div>${body}</div>`;document.body.appendChild(m);m.addEventListener('click',ev=>{if(ev.target===m)closeModal(id)});m.querySelector('[data-close]')?.addEventListener('click',()=>closeModal(id));return m}

  function renderTrackCards(){const grid=$('trackGrid');if(!grid)return;grid.innerHTML=tracks.map((t,i)=>`<button class="track-card magnetic reveal-up ${i===idx?'selected':''}" data-index="${i}" data-tags="${t.tags.join(' ')}"><div class="track-head"><span>${String(i+1).padStart(2,'0')}</span><span>${fmt(t.duration)}</span></div><div class="track-art ${t.art}"><i></i><b></b></div><div class="track-info"><div><strong>${t.title}</strong><small>${t.artist}</small></div><em>${t.bpm}</em></div></button>`).join('');bindCards()}
  function bindCards(){$$('.track-card').forEach(c=>c.addEventListener('click',()=>select(+c.dataset.index)));$$('.track-card').forEach(c=>c.addEventListener('pointermove',ev=>{const r=c.getBoundingClientRect();c.style.setProperty('--mx',`${((ev.clientX-r.left)/r.width)*100}%`);c.style.setProperty('--my',`${((ev.clientY-r.top)/r.height)*100}%`)}))}

  function setupBars(){const b=els.bars;if(!b)return;b.innerHTML='';for(let i=0;i<42;i++){const x=document.createElement('i');x.style.height=`${18+Math.random()*55}%`;b.appendChild(x)}}
  function ensureLyrics(){const t=tracks[idx];if(!els.lyricCopy)return;els.lyricCopy.innerHTML=t.lyrics.map((line,i)=>`<p class="lyric-line ${i===0?'active':''}" data-time="${Math.round(i*t.duration/Math.max(1,t.lyrics.length))}">${line}</p>`).join('')}

  function audioInit(){if(audioCtx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audioCtx=new C();masterGain=audioCtx.createGain();masterGain.gain.value=muted?0:.045;masterGain.connect(audioCtx.destination)}
  function tone(freq=180,d=.16,vol=.035){if(!audioCtx||!playing||muted)return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(vol,now+.01);g.gain.exponentialRampToValueAtTime(.001,now+d);o.connect(g).connect(masterGain);o.start(now);o.stop(now+d)}
  function start(){audioInit();try{audioCtx?.resume()}catch{}playing=true;if(els.play)els.play.textContent='❚❚';if(els.dockPlay)els.dockPlay.querySelector('span').textContent='❚❚';clearInterval(timer);timer=setInterval(()=>{pos+=.1;update();animateSignal();if(pos>=tracks[idx].duration){select((idx+1)%tracks.length,true)}},100);tone(tracks[idx].bpm>115?235:165,.2,.02);syncMedia()}
  function stop(){playing=false;if(els.play)els.play.textContent='▶';if(els.dockPlay)els.dockPlay.querySelector('span').textContent='▶';clearInterval(timer);timer=null;syncMedia()}
  function toggle(){playing?stop():start()}
  function select(i,keepPlaying=false){idx=(i+tracks.length)%tracks.length;pos=0;render();if(keepPlaying||playing){playing=false;clearInterval(timer);start()}viewTransition(()=>{});updateShareMeta()}
  function update(){const t=tracks[idx];els.current.textContent=fmt(pos);els.duration.textContent=fmt(t.duration);els.progress.max=t.duration;els.progress.value=pos;els.playerTitle.textContent=t.title;els.playerArtist.textContent=t.artist;els.playerThumb.className=`player-thumb ${t.art}`;els.heroTrack.textContent=t.title;els.heroArtist.textContent=t.artist;els.heroEnergy.textContent=`${t.bpm} BPM`;els.heroMood.textContent=t.mood;els.albumTitle.innerHTML=t.title.toUpperCase().replace(/ /g,'<br>');els.albumBpm.textContent=`${t.bpm} BPM`;els.albumNumber.textContent=String(idx+1).padStart(3,'0');els.signalBpm.textContent=t.bpm;els.sceneTrack.textContent=t.title.toUpperCase();els.sceneMood.textContent=t.mood.toUpperCase();els.lyricName.textContent=t.title.toUpperCase();els.lyricDuration.textContent=fmt(t.duration);els.lyricClock.textContent=fmt(pos);els.lyricProgress?.querySelector('i')?.style.setProperty('height',`${pos/t.duration*100}%`);$$('.track-card').forEach((c,i)=>c.classList.toggle('selected',i===idx));let active=0;$$('.lyric-line').forEach((l,i)=>{if(pos>=+l.dataset.time)active=i;l.classList.toggle('active',i===active)});syncMedia();}
  function render(){ensureLyrics();update();}
  function animateSignal(){const t=tracks[idx],b=Date.now()/1000*(t.bpm/60);$$('#signalBars i').forEach((x,i)=>x.style.height=`${18+Math.abs(Math.sin(b*1.45+i*.72))*76}%`);const pulse=1+Math.sin(b*Math.PI*2)*.012;els.album?.classList.toggle('is-beat',Math.sin(b*Math.PI*2)>.88);if(els.album)els.album.style.scale=playing?pulse:1}

  function setupCanvas(){const c=els.space;if(!c)return;const ctx=c.getContext('2d',{alpha:true});let w=innerWidth,h=innerHeight,dpr=1,pts=[];const density=()=>innerWidth<600?75:innerWidth<1000?130:220;function resize(){dpr=Math.min(devicePixelRatio||1,1.5);w=innerWidth;h=innerHeight;c.width=Math.floor(w*dpr);c.height=Math.floor(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);pts=Array.from({length:density()},()=>({x:Math.random()*w,y:Math.random()*h,z:.2+Math.random()*.9,s:.3+Math.random()*1.6,phase:Math.random()*Math.PI*2}))}function frame(t){if(motion){ctx.clearRect(0,0,w,h);const tempo=tracks[idx].bpm/110;for(const p of pts){p.y-=p.s*tempo*.45;if(p.y<-10)p.y=h+10;p.x+=Math.sin(t*.0004+p.phase)*.08;const glow=1+Math.sin(t*.002+p.phase)*.35;ctx.globalAlpha=.12+.2*p.z;ctx.fillStyle='rgb(173,160,255)';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.5,p.z*glow),0,Math.PI*2);ctx.fill()}}requestAnimationFrame(frame)}addEventListener('resize',resize);resize();requestAnimationFrame(frame)}

  function setupPointer(){if(!matchMedia('(pointer:fine)').matches||!els.cursor)return;let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',ev=>{tx=ev.clientX;ty=ev.clientY;document.documentElement.style.setProperty('--pointer-x',`${tx/innerWidth*100}%`);document.documentElement.style.setProperty('--pointer-y',`${ty/innerHeight*100}%`)},{passive:true});function loop(){x+=(tx-x)*.14;y+=(ty-y)*.14;els.cursor.style.left=x+'px';els.cursor.style.top=y+'px';if(els.cursorLabel){els.cursorLabel.style.left=x+'px';els.cursorLabel.style.top=y+'px'}requestAnimationFrame(loop)}loop();$$('[data-cursor],.magnetic').forEach(el=>{el.addEventListener('mouseenter',()=>{els.cursor.classList.add('is-hover');if(el.dataset.cursor){els.cursorLabel.textContent=el.dataset.cursor;els.cursorLabel.classList.add('show')}});el.addEventListener('pointermove',ev=>{if(!motion||!el.classList.contains('magnetic'))return;const r=el.getBoundingClientRect();el.style.translate=`${(ev.clientX-(r.left+r.width/2))*.1}px ${(ev.clientY-(r.top+r.height/2))*.1}px`});el.addEventListener('mouseleave',()=>{els.cursor.classList.remove('is-hover');els.cursorLabel.classList.remove('show');el.style.translate=''})})}
  function setupTouch3D(){if(!els.world||!els.rig)return;els.world.addEventListener('pointermove',ev=>{const r=els.world.getBoundingClientRect(),nx=(ev.clientX-r.left)/r.width-.5,ny=(ev.clientY-r.top)/r.height-.5;els.rig.style.transform=`rotateX(${ny*-13}deg) rotateY(${nx*18}deg)`;$$('[data-depth]').forEach(x=>{const dep=+(x.dataset.depth||1);x.style.translate=`${nx*18*dep}px ${ny*-14*dep}px`})},{passive:true});els.world.addEventListener('pointerleave',()=>{els.rig.style.transform='';$$('[data-depth]').forEach(x=>x.style.translate='')});addEventListener('deviceorientation',ev=>{if(!motion||matchMedia('(pointer:fine)').matches)return;const gx=Math.max(-22,Math.min(22,ev.gamma||0)),by=Math.max(-20,Math.min(20,(ev.beta||40)-40));els.rig.style.transform=`rotateX(${by*.2}deg) rotateY(${gx*.3}deg)`})}

  function setupGSAP(){if(!window.gsap||!window.ScrollTrigger||!motion)return;gsap.registerPlugin(ScrollTrigger);gsap.fromTo(els.nav,{y:'-120%'},{y:0,duration:1,ease:'power4.out',delay:.2});gsap.fromTo('.title-line',{y:'115%'},{y:'0%',duration:1.0,stagger:.11,ease:'power4.out',delay:.2});gsap.fromTo('.hero-sub,.hero-actions,.hero-meta,.eyebrow-row',{y:24,opacity:0},{y:0,opacity:1,duration:.7,stagger:.06,ease:'power3.out',delay:.55});gsap.fromTo(els.rig,{scale:.72,y:80,opacity:0},{scale:1,y:0,opacity:1,duration:1.25,ease:'expo.out',delay:.3});gsap.to(els.world,{y:-70,scrollTrigger:{trigger:'#hero',start:'top top',end:'bottom top',scrub:1}});$$('.reveal,.reveal-up').forEach((el,i)=>gsap.fromTo(el,{y:45,opacity:0,scale:.97},{y:0,opacity:1,scale:1,duration:.8,delay:(i%5)*.04,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%',once:true}}));gsap.to('.ticker',{xPercent:-20,scrollTrigger:{trigger:'.intro-strip',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.lyrics-depth-word',{x:180,rotate:16,scrollTrigger:{trigger:'#lyrics',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.lab-grid',{yPercent:-10,rotation:10,scrollTrigger:{trigger:'#visualLab',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.cinema-orb',{y:100,rotation:90,scrollTrigger:{trigger:'.cinema-orb',start:'top bottom',end:'bottom top',scrub:1}})}

  function setupFilters(){
    $$('.filter').forEach(b=>b.addEventListener('click',()=>{mood=b.dataset.filter||'all';persist();$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.track-card').forEach(c=>c.classList.toggle('is-hidden',mood!=='all'&&!c.dataset.tags.split(' ').includes(mood)));if($('filterStatus'))$('filterStatus').textContent=mood==='all'?'LIVE RADAR · CURATED':'FILTER · '+mood.toUpperCase()}));
  }

  function addLauncher(){
    const nav=document.querySelector('.nav-actions')||document.querySelector('.nav-actions');
    const b=document.createElement('button');b.className='nav-pill magnetic';b.textContent='VYBE HUB';b.dataset.cursor='HUB';b.id='hubButton';b.onclick=()=>openHub();nav?.insertBefore(b,nav.firstChild);
    const mobile=document.querySelector('.mobile-dock');
    if(mobile&&!$('hubDock')){const x=document.createElement('button');x.id='hubDock';x.innerHTML='<span>✦</span><small>Hub</small>';x.onclick=()=>openHub();mobile.insertBefore(x,mobile.lastElementChild)}
  }

  function openHub(){
    const body=`<div class="vybe-grid">
      <button class="vybe-card" data-open-feature="mood"><span class="vybe-pill">DISCOVER</span><strong>VYBE Mood</strong><p>Pick a feeling and tune the discovery world.</p></button>
      <button class="vybe-card" data-open-feature="feed"><span class="vybe-pill">FEED</span><strong>VYBE Feed</strong><p>See curated signals, recent requests and new artist submissions.</p></button>
      <button class="vybe-card" data-open-feature="playlists"><span class="vybe-pill">LIBRARY</span><strong>Playlists & Library</strong><p>Like tracks, create playlists and save your own VYBE.</p></button>
      <button class="vybe-card" data-open-feature="request"><span class="vybe-pill">COMMUNITY</span><strong>Request a song</strong><p>Ask VYBE to consider a famous or loved song.</p></button>
      <button class="vybe-card" data-open-feature="submit"><span class="vybe-pill">ARTISTS</span><strong>Submit your music</strong><p>Send your song for human review before publishing.</p></button>
      <button class="vybe-card" data-open-feature="studio"><span class="vybe-pill">TEAM</span><strong>VYBE Studio</strong><p>Review artist submissions and curate the catalogue.</p></button>
      <button class="vybe-card" data-open-feature="share"><span class="vybe-pill">GROW</span><strong>Share this VYBE</strong><p>Create a shareable song link for this exact experience.</p></button>
      <button class="vybe-card" data-open-feature="about"><span class="vybe-pill">SYSTEM</span><strong>VYBE Tech</strong><p>3D motion, kinetic lyrics, responsive layout and accessibility.</p></button>
    </div>`;
    const m=modalShell('hubModal','Enter the VYBE system',body);m.querySelectorAll('[data-open-feature]').forEach(x=>x.addEventListener('click',()=>openFeature(x.dataset.openFeature)));openModal('hubModal')
  }

  function openFeature(type){closeModal('hubModal');setTimeout(()=>{
    if(type==='mood')return openMood();
    if(type==='feed')return openFeed();
    if(type==='playlists')return openPlaylists();
    if(type==='request')return openRequest();
    if(type==='submit')return openSubmit();
    if(type==='studio')return openStudio();
    if(type==='share')return shareCurrent();
    openAbout();
  },120)}

  function openMood(){
    const moods=[['all','All'],['love','Love'],['night','Late Night'],['hype','Hype'],['sad','Sad'],['chill','Chill'],['workout','Workout'],['party','Party']];
    const m=modalShell('moodModal','How are you feeling?',`<div class="vybe-tabs">${moods.map(x=>`<button class="vybe-btn vybe-tab ${mood===x[0]?'active':''}" data-mood="${x[0]}">${x[1]}</button>`).join('')}</div><div class="vybe-card"><strong id="moodResult">${mood==='all'?'Curated VYBE':'VYBE · '+mood.toUpperCase()}</strong><p>Choose a mood and VYBE will filter the current curated catalogue. The visual world keeps the same mood language.</p></div>`);m.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;persist();$$('.filter').forEach(f=>f.classList.toggle('active',f.dataset.filter===mood||mood==='all'&&f.dataset.filter==='all'));$$('.track-card').forEach(c=>c.classList.toggle('is-hidden',mood!=='all'&&!c.dataset.tags.split(' ').includes(mood)));m.querySelector('#moodResult').textContent=mood==='all'?'Curated VYBE':'VYBE · '+mood.toUpperCase();showToast('VYBE mood updated')});openModal('moodModal')
  }

  function openFeed(){
    const popular=[...tracks].slice(0,4).map((t,i)=>`<div class="vybe-card"><span class="vybe-pill">${i<2?'RISING':'CURATED'}</span><strong>${t.title}</strong><p>${t.artist} · ${t.mood}</p><div class="vybe-actions"><button class="vybe-btn primary" data-play="${i}">Play</button><button class="vybe-btn" data-share="${i}">Share</button></div></div>`).join('');
    const req=requests.slice().sort((a,b)=>b.votes-a.votes).slice(0,3).map(r=>`<div class="vybe-stat"><strong>${r.title}</strong><span>♥ ${r.votes} requests</span></div>`).join('');
    const m=modalShell('feedModal','VYBE Feed',`<div class="vybe-grid">${popular}</div><h4 style="margin-top:22px">Most requested</h4><div class="vybe-card">${req||'<div class="vybe-empty">No requests yet.</div>'}</div>`);
    m.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{select(+b.dataset.play);start();closeModal('feedModal')});m.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>{select(+b.dataset.share);shareCurrent()});openModal('feedModal')
  }

  function openPlaylists(){
    const list=playlists.map(p=>`<div class="vybe-card"><strong>${p.name}</strong><p>${p.tracks.length} saved tracks</p><div class="vybe-actions"><button class="vybe-btn" data-view-playlist="${p.id}">View</button></div></div>`).join('');
    const likedList=[...liked].map(i=>tracks[i]).filter(Boolean).map((t,i)=>`<div class="vybe-stat"><strong>${t.title}</strong><span>${t.artist}</span></div>`).join('')||'<div class="vybe-empty">Like a track to build your library.</div>';
    const m=modalShell('libraryModal','Your VYBE Library',`<div class="vybe-actions"><button class="vybe-btn primary" id="newPlaylist">+ New playlist</button><button class="vybe-btn" id="clearLikes">Clear likes</button></div><h4>Playlists</h4><div class="vybe-grid">${list}</div><h4 style="margin-top:22px">Liked tracks</h4><div class="vybe-card">${likedList}</div>`);
    m.querySelector('#newPlaylist').onclick=()=>{const name=prompt('Playlist name?','Night VYBE');if(!name)return;playlists.push({id:'p-'+Date.now(),name,tracks:[]});persist();closeModal('libraryModal');openPlaylists()};m.querySelector('#clearLikes').onclick=()=>{liked.clear();persist();closeModal('libraryModal');openPlaylists()};m.querySelectorAll('[data-view-playlist]').forEach(b=>b.onclick=()=>{const p=playlists.find(x=>x.id===b.dataset.viewPlaylist);if(!p)return;showToast(`${p.name}: ${p.tracks.length} tracks`)})
    openModal('libraryModal')
  }

  function openRequest(){
    const rows=requests.sort((a,b)=>b.votes-a.votes).map(r=>`<div class="vybe-request-row"><div class="line"><strong>${r.title}</strong><span>♥ ${r.votes}</span></div><p>${r.artist}</p><div class="vybe-row-actions"><button class="vybe-btn" data-vote="${r.id}">Support request</button></div></div>`).join('');
    const m=modalShell('requestModal','Request a song',`<form id="requestForm"><label class="vybe-label">Song</label><input class="vybe-input" name="title" required placeholder="Song name"><label class="vybe-label">Artist</label><input class="vybe-input" name="artist" required placeholder="Artist name"><label class="vybe-label">Why should VYBE add it?</label><textarea class="vybe-textarea" name="reason" placeholder="Tell us why people love it…"></textarea><button class="vybe-btn primary" type="submit">Submit request</button></form><h4 style="margin-top:24px">Most requested</h4>${rows||'<div class="vybe-empty">Be the first request.</div>'}`);
    m.querySelector('#requestForm').onsubmit=ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);const title=fd.get('title'),artist=fd.get('artist');const hit=requests.find(r=>r.title.toLowerCase()===String(title).toLowerCase()&&r.artist.toLowerCase()===String(artist).toLowerCase());if(hit)hit.votes++;else requests.push({id:Date.now(),title,artist,votes:1,status:'Requested'});persist();showToast('Song request submitted');closeModal('requestModal');openRequest()};m.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{const r=requests.find(x=>x.id==b.dataset.vote);if(r){r.votes++;persist();showToast('Request supported');closeModal('requestModal');openRequest()}});openModal('requestModal')
  }

  function openSubmit(){
    const m=modalShell('submitModal','Submit your music',`<form id="submitForm"><p>Artists can submit music for VYBE consideration. Every submission remains <strong>Under Review</strong> until a human reviewer approves it.</p><label class="vybe-label">Artist / project</label><input class="vybe-input" name="artist" required placeholder="Artist name"><label class="vybe-label">Email</label><input class="vybe-input" name="email" type="email" required placeholder="you@example.com"><label class="vybe-label">Song title</label><input class="vybe-input" name="title" required placeholder="Song title"><label class="vybe-label">Genre</label><select class="vybe-select" name="genre"><option>Pop</option><option>Hip-Hop</option><option>Punjabi</option><option>Hindi</option><option>Electronic</option><option>Indie</option><option>Other</option></select><label class="vybe-label">Song / preview URL</label><input class="vybe-input" name="url" type="url" placeholder="https://…"><label class="vybe-label">Lyrics</label><textarea class="vybe-textarea" name="lyrics" placeholder="Paste lyrics you are authorized to provide"></textarea><label class="vybe-label">Audio file (local preview)</label><input class="vybe-input" name="audio" type="file" accept="audio/*"><label style="display:flex;gap:8px;align-items:flex-start;font-size:11px;color:#9a9aa2"><input name="rights" type="checkbox" required> I confirm I have the necessary rights/permissions to submit this recording and lyrics.</label><div class="vybe-actions"><button class="vybe-btn primary" type="submit">Submit for human review</button></div></form>`);
    m.querySelector('#submitForm').onsubmit=ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);const file=fd.get('audio');const sub={id:'VYBE-'+Math.random().toString(36).slice(2,7).toUpperCase(),artist:fd.get('artist'),email:fd.get('email'),title:fd.get('title'),genre:fd.get('genre'),url:fd.get('url'),lyrics:fd.get('lyrics'),audioName:file?.name||'',status:'Under Review',createdAt:new Date().toISOString()};submissions.unshift(sub);persist();showToast('Submission sent for human review');closeModal('submitModal')};openModal('submitModal')
  }

  function openStudio(){
    const stats=`<div class="vybe-grid"><div class="vybe-card"><span class="vybe-pill">QUEUE</span><strong>${submissions.filter(s=>s.status==='Under Review').length}</strong><p>Waiting for review</p></div><div class="vybe-card"><span class="vybe-pill">REQUESTS</span><strong>${requests.length}</strong><p>Community song requests</p></div><div class="vybe-card"><span class="vybe-pill">CATALOGUE</span><strong>${tracks.length}</strong><p>Curated demo signals</p></div></div>`;
    const rows=submissions.map(s=>`<div class="vybe-review-row"><div class="line"><strong>${s.title}</strong><span>${s.status}</span></div><p>${s.artist} · ${s.genre} · ${new Date(s.createdAt).toLocaleDateString()}</p><small>${s.audioName||'No local audio'}${s.url?' · '+s.url:''}</small><div class="vybe-row-actions"><button class="vybe-btn" data-review="approve" data-id="${s.id}">Approve</button><button class="vybe-btn" data-review="changes" data-id="${s.id}">Request changes</button><button class="vybe-btn" data-review="reject" data-id="${s.id}">Reject</button></div></div>`).join('')||'<div class="vybe-empty">No submissions yet. Use Submit Your Music.</div>';
    const m=modalShell('studioModal','VYBE Studio',`${stats}<h4 style="margin-top:24px">Human review queue</h4>${rows}<p style="margin-top:22px;color:#777780;font-size:10px">Studio data is local to this browser in the GitHub Pages build. A shared production Studio will use a secure backend so multiple reviewers can work together.</p>`);
    m.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const s=submissions.find(x=>x.id===b.dataset.id);if(!s)return;if(b.dataset.review==='approve'){s.status='Approved';if(!tracks.some(t=>t.title===s.title&&t.artist===s.artist)){tracks.push({title:s.title,artist:s.artist,bpm:100,mood:'Fresh · Submitted',tags:['all','new'],duration:150,art:'art-a',lyrics:(s.lyrics?s.lyrics.split(/\n+/).filter(Boolean):['Artist submitted a new signal','Lyrics preview available in VYBE','Sound becomes space','Welcome to the experience']).slice(0,6)});renderTrackCards();}}else if(b.dataset.review==='changes')s.status='Changes Required';else s.status='Rejected';persist();closeModal('studioModal');openStudio();showToast(`Submission ${s.status.toLowerCase()}`)});openModal('studioModal')
  }

  function openAbout(){
    const m=modalShell('aboutModal','Built for every screen',`<div class="vybe-grid"><div class="vybe-card"><strong>Phone</strong><p>Touch, swipe, motion tilt where supported, compact player and bottom navigation.</p></div><div class="vybe-card"><strong>Tablet</strong><p>Adaptive two-column compositions and hybrid pointer/touch behavior.</p></div><div class="vybe-card"><strong>Desktop</strong><p>Custom cursor, magnetic buttons, 3D depth and scroll choreography.</p></div><div class="vybe-card"><strong>TV / Large screen</strong><p>Large type, distance-friendly controls, keyboard/remote-compatible actions and fullscreen.</p></div><div class="vybe-card"><strong>Motion engine</strong><p>GSAP/ScrollTrigger plus a lightweight canvas visual field, with reduced-motion support.</p></div><div class="vybe-card"><strong>Music model</strong><p>Curated catalogue, community requests, human-reviewed artist submissions and future licensed providers.</p></div></div>`);openModal('aboutModal')
  }

  async function shareCurrent(){const t=tracks[idx], url=`${location.origin}${location.pathname}#song-${encodeURIComponent(t.title.replace(/\s+/g,'-').toLowerCase())}`;const data={title:`${t.title} · VYBE`,text:`Listen to ${t.title} by ${t.artist} in VYBE.`,url};try{if(navigator.share){await navigator.share(data)}else{await navigator.clipboard.writeText(url);showToast('VYBE link copied')}}catch(e){if(e?.name!=='AbortError')showToast('Share cancelled')}}
  function updateShareMeta(){document.title=`${tracks[idx].title} · VYBE`}

  async function wake(){if(!('wakeLock' in navigator)){showToast('Wake Lock is not supported here');return}try{if(wakeLock){await wakeLock.release();wakeLock=null;$('wakeButton').textContent='WAKE';showToast('Screen wake off')}else{wakeLock=await navigator.wakeLock.request('screen');$('wakeButton').textContent='AWAKE';showToast('Screen will stay awake');wakeLock.addEventListener('release',()=>{wakeLock=null;$('wakeButton').textContent='WAKE'})}}catch{showToast('Wake Lock permission was not granted')}}
  async function fullscreen(){try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{showToast('Fullscreen is not available')}}
  function syncMedia(){if(!('mediaSession' in navigator))return;const t=tracks[idx];try{navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:'VYBE',artwork:[]});navigator.mediaSession.playbackState=playing?'playing':'paused'}catch{}}

  function setupPreloader(){let p=0;const started=performance.now();function finish(){els.preP&&(els.preP.style.width='100%');els.preL&&(els.preL.textContent='LOADING EXPERIENCE 100%');setTimeout(()=>els.pre?.classList.add('loaded'),reduced?30:260)}const id=setInterval(()=>{p=Math.min(100,p+(p<60?8:18));if(els.preP)els.preP.style.width=p+'%';if(els.preL)els.preL.textContent=`LOADING EXPERIENCE ${String(p).padStart(2,'0')}%`;if(p>=100){clearInterval(id);finish()}},reduced?20:38);setTimeout(()=>{clearInterval(id);finish()},1800)}

  function setupControls(){
    $('prevButton')?.addEventListener('click',()=>select(idx-1));$('nextButton')?.addEventListener('click',()=>select(idx+1));els.play?.addEventListener('click',toggle);els.dockPlay?.addEventListener('click',toggle);$('finalPlayButton')?.addEventListener('click',toggle);$('progress')?.addEventListener('input',()=>{pos=+$('progress').value;update()});$('muteButton')?.addEventListener('click',()=>{muted=!muted;if(masterGain)masterGain.gain.value=muted?0:.045;$('muteButton').textContent=muted?'MUTE':'VOL';showToast(muted?'Muted':'Sound on')});$('shuffleButton')?.addEventListener('click',()=>select(Math.floor(Math.random()*tracks.length)));$('wakeButton')?.addEventListener('click',wake);$('fullscreenButton')?.addEventListener('click',fullscreen);$('sheetFullscreen')?.addEventListener('click',fullscreen);$('sheetWake')?.addEventListener('click',wake);$('experienceButton')?.addEventListener('click',()=>{start();$('playerScene')?.scrollIntoView({behavior:reduced?'auto':'smooth'})});$('lyricsModeButton')?.addEventListener('click',()=>{document.body.classList.toggle('focus-mode');$('lyricsModeButton').textContent=document.body.classList.contains('focus-mode')?'EXIT FOCUS':'FOCUS MODE'});
    $('dockMore')?.addEventListener('click',()=>openHub());$('closeMore')?.addEventListener('click',()=>closeModal('moreSheet'));$('sheetMotion')?.addEventListener('click',()=>{motion=!motion;document.body.classList.toggle('motion-off',!motion);$('sheetMotion').querySelector('span').textContent=motion?'ON':'OFF';showToast(motion?'Motion on':'Motion off')});
    document.addEventListener('click',ev=>{const a=ev.target.closest('a[href^="#"]');if(!a||!a.getAttribute('href'))return;const id=a.getAttribute('href').slice(1),target=document.getElementById(id);if(!target)return;ev.preventDefault();viewTransition(()=>target.scrollIntoView({behavior:reduced?'auto':'smooth'}))});
    window.addEventListener('keydown',ev=>{if(ev.key==='Escape'){closeModal('searchModal');closeModal('moreSheet');$$('.vybe-modal').forEach(m=>m.classList.remove('open'))}if(ev.code==='Space'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){ev.preventDefault();toggle()}if(ev.key==='ArrowRight'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))select(idx+1);if(ev.key==='ArrowLeft'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))select(idx-1);if(ev.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){ev.preventDefault();openSearch()}});
    window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;if(els.scroll)els.scroll.style.transform=`scaleX(${max?scrollY/max:0})`},{passive:true});
  }
  function openSearch(){const m=els.search;if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');const input=els.searchInput,box=els.searchResults;const draw=q=>{const z=String(q||'').toLowerCase();const a=tracks.filter(t=>(t.title+' '+t.artist+' '+t.mood+' '+t.tags.join(' ')).toLowerCase().includes(z));box.innerHTML=a.map(t=>`<button class="result" data-i="${tracks.indexOf(t)}"><span><strong>${t.title}</strong><small>${t.artist} · ${t.mood}</small></span><em>${fmt(t.duration)}</em></button>`).join('')||'<div class="result"><strong>No signal found.</strong></div>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{select(+b.dataset.i);start();closeSearch()})};const closeSearch=()=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')};$('closeSearch')?.addEventListener('click',closeSearch);m.addEventListener('click',ev=>{if(ev.target===m)closeSearch()},{once:true});input.value='';draw('');input.oninput=()=>draw(input.value);$$('.search-suggestions button').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;draw(b.dataset.query)});setTimeout(()=>input.focus(),80)}

  function seedFeatureButtons(){
    document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>openFeature(b.dataset.feature)));
  }

  function init(){
    injectFeatureStyles();setupPreloader();setupCanvas();setupPointer();setupTouch3D();setupBars();renderTrackCards();setupFilters();setupControls();addLauncher();seedFeatureButtons();
    try{setupGSAP()}catch(e){console.warn('VYBE motion fallback',e)}
    render();
    if(matchMedia('(prefers-reduced-motion: reduce)').matches){motion=false;document.body.classList.add('motion-off')}
    if('mediaSession' in navigator){try{navigator.mediaSession.setActionHandler('play',start);navigator.mediaSession.setActionHandler('pause',stop);navigator.mediaSession.setActionHandler('nexttrack',()=>select(idx+1));navigator.mediaSession.setActionHandler('previoustrack',()=>select(idx-1))}catch{}}
    if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
    document.querySelector('.brand')?.addEventListener('dblclick',()=>showToast('Welcome to VYBE'));
    document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&wakeLock===null&&playing&&navigator.wakeLock){/* user can re-enable from WAKE */}});
  }

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
